# Use the official node image as a parent image
FROM node:18

# Set the working directory
WORKDIR /app

# COPY ./chain/out ./chain/out
COPY . .

# Install dependencies and setup
RUN npm install -g pnpm && pnpm install

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
