name: CI
on: push
jobs:
    node:
        name: Node
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  submodules: recursive
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: "24"
            - name: Install pnpm
              uses: pnpm/action-setup@v6
            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - name: Setup pnpm cache
              uses: actions/cache@v5
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - name: Install
              run: pnpm install --frozen-lockfile
            - name: Lint main
              run: pnpm lint
            - name: Lint docs
              run: pnpm --filter tap-docs lint
            - name: Lint app
              run: pnpm --filter tap-app lint
            - name: Typecheck app
              run: pnpm --filter tap-app typecheck
            - name: Test units
              run: pnpm test:units

    foundry:
        name: Foundry
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  submodules: recursive
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
            - name: Forge test
              working-directory: chain
              run: forge test
